ci: disable Coverity on the `main` branch temporarily
The service has been down for quite some time now causing the CI to fail:
```
curl https://scan.coverity.com/download/other/linux64 \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    59    0     0  100    59      0    378 --:--:-- --:--:-- --:--:--   378
100  1608    0  1549  100    59   7470    284 --:--:-- --:--:-- --:--:--  7730
Error: Unable to process file command 'output' successfully.
Error: Invalid format '  <head>'
```