cscppc: run cppcheck with -D__STDC__
... to avoid the following error:

/usr/include/sys/cdefs.h:31: error: preprocessorErrorDirective: #error "You need a ISO C conforming compiler to use the glibc headers" <--[cppcheck]

... produced by the following code:

    /* The GNU libc does not support any K&R compilers or the traditional mode
       of ISO C compilers anymore.  Check for some of the combinations not
       anymore supported.  */
    #if defined __GNUC__ && !defined __STDC__
    # error "You need a ISO C conforming compiler to use the glibc headers"
    #endif