cswrap-core: fix a warning introduced in the last commit
Error: COMPILER_WARNING:
cswrap-core.c: scope_hint: In function ‘launch_tool’
cswrap-core.c:160:9: warning: suggest parentheses around assignment used as truth value [-Wparentheses]