packaging: make the spec file compatible with EPEL-7 again
rpmbuild in EPEL-7 does not support weak dependencies:
```
[...]
Start: buildsrpm
Start: rpmbuild -bs
error: line 63: Unknown tag: Recommends: smatch
Building target platforms: x86_64
Building for target x86_64
Finish: rpmbuild -bs
Finish: buildsrpm
ERROR: Exception(/var/lib/copr-rpmbuild/workspace/workdir-y7rr3tva/cscppc/cscppc.spec) Config(centos+epel-7-x86_64) 1 minutes 19 seconds
```

Fixes: commit 77112754b1bd846045a0dea8268c0197249de986
Closes: https://github.com/csutils/cscppc/pull/40